/* eslint-disable */
// WARNING: Do not edit this file

const ebconfig = {
  "integration": "react-1-YBsyWa2XgJiG0H3XOila9rZ7BJqQktaC-3YBa-QbR0scb6uFBtekqXvSgtZzr5ZeCOJY43IRGHa-Ja2VgNFuH00SOFNerf4dvbdhQaZNx5p2--mgwvzc4lay",
  "tt": "tt-1-LZuTLXD98hZs5wI2ingztImsXRytHtnDk-1I54Nnp-I=",
  "version": "2020-11-20"
}

export default ebconfig;